language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - Pharo-6.0

jobs:
  include:
    - stage: bash-test
      script: ./bash-test.sh
    - stage: test
      skip_cleanup: true
    - stage: lint
      script: ./qa-testing.sh
